# Generated by Django 3.1.7 on 2021-04-22 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0007_auto_20180812_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='min_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
