# Generated by Django 3.1.7 on 2021-04-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0011_auto_20210422_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='image',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
